# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1

FROM golang:1.24.3-alpine AS builder
WORKDIR /workspace

# Install git for dependencies
RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN cd cmd/server && go build -o server

FROM alpine:latest
RUN apk add --no-cache ca-certificates
WORKDIR /app
COPY --from=builder /workspace/cmd/server/server ./

EXPOSE 8080
ENTRYPOINT ["./server"]
